export const documentationService = {
  createDatabaseMarkdownReport({
    connection = null,
    schemaOverview = null,
    activeTable = "",
    activeSchema = "",
    activeColumns = [],
    generatedBy = "DBPilot Studio"
  } = {}) {
    const now = new Date().toISOString();

    const lines = [];

    lines.push(`# DBPilot Studio - Database Report`);
    lines.push("");
    lines.push(`Generated at: ${now}`);
    lines.push(`Generated by: ${generatedBy}`);
    lines.push("");

    if (connection) {
      lines.push(`## Connection`);
      lines.push("");
      lines.push(`| Field | Value |`);
      lines.push(`| --- | --- |`);
      lines.push(`| Name | ${escapeMarkdown(connection.name || "-")} |`);
      lines.push(`| Engine | ${escapeMarkdown(connection.engine || "-")} |`);
      lines.push(`| Host | ${escapeMarkdown(connection.host || connection.filePath || "-")} |`);
      lines.push(`| Database | ${escapeMarkdown(connection.database || connection.filePath || "-")} |`);
      lines.push(`| Readonly | ${connection.readonly ? "Yes" : "No"} |`);
      lines.push("");
    }

    if (schemaOverview?.summary) {
      lines.push(`## Summary`);
      lines.push("");
      lines.push(`| Metric | Value |`);
      lines.push(`| --- | ---: |`);
      lines.push(`| Schemas | ${schemaOverview.summary.schemas || 0} |`);
      lines.push(`| Tables | ${schemaOverview.summary.tables || 0} |`);
      lines.push(`| Views | ${schemaOverview.summary.views || 0} |`);
      lines.push(`| Estimated Rows | ${schemaOverview.summary.estimatedRows || 0} |`);
      lines.push("");
    }

    if (Array.isArray(schemaOverview?.tables) && schemaOverview.tables.length) {
      lines.push(`## Schemas and Tables`);
      lines.push("");

      schemaOverview.tables.forEach((schema) => {
        lines.push(`### ${escapeMarkdown(schema.name)}`);
        lines.push("");
        lines.push(`| Type | Name | Columns | Rows |`);
        lines.push(`| --- | --- | ---: | ---: |`);

        schema.tables.forEach((table) => {
          lines.push(
            `| ${escapeMarkdown(table.type || "table")} | ${escapeMarkdown(table.name)} | ${table.columns || 0} | ${table.rows || 0} |`
          );
        });

        lines.push("");
      });
    }

    if (activeTable && activeColumns.length) {
      lines.push(`## Active Table Structure`);
      lines.push("");
      lines.push(`Table: \`${activeSchema ? `${activeSchema}.` : ""}${activeTable}\``);
      lines.push("");
      lines.push(`| Column | Type | Nullable | Primary Key | Default |`);
      lines.push(`| --- | --- | --- | --- | --- |`);

      activeColumns.forEach((column) => {
        lines.push(
          `| ${escapeMarkdown(column.name)} | ${escapeMarkdown(column.type || column.rawType || "-")} | ${column.nullable ? "YES" : "NO"} | ${column.primaryKey ? "YES" : "NO"} | ${escapeMarkdown(column.defaultValue || "-")} |`
        );
      });

      lines.push("");
    }

    lines.push(`---`);
    lines.push("");
    lines.push(`Report created with DBPilot Studio.`);

    return lines.join("\n");
  },

  createHistoryMarkdownReport(history = []) {
    const lines = [];

    lines.push(`# DBPilot Studio - History Report`);
    lines.push("");
    lines.push(`Generated at: ${new Date().toISOString()}`);
    lines.push("");
    lines.push(`| Date | Type | Status | Detail |`);
    lines.push(`| --- | --- | --- | --- |`);

    history.forEach((item) => {
      lines.push(
        `| ${escapeMarkdown(item.createdAt || "-")} | ${escapeMarkdown(item.type || "-")} | ${escapeMarkdown(item.status || "-")} | ${escapeMarkdown(item.detail || item.query || "-")} |`
      );
    });

    return lines.join("\n");
  }
};

function escapeMarkdown(value) {
  return String(value ?? "")
    .replaceAll("|", "\\|")
    .replaceAll("\n", " ")
    .replaceAll("\r", " ");
}